services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
# TODO add volume
    environment:
      POSTGRES_PASSWORD: 12345678
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
